# Generated by Django 5.1.1 on 2024-11-14 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('language', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='dictionary__user_id_b44fcb_idx'), models.Index(fields=['language'], name='dictionary__languag_8733f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='dictionary_service.dictionary')),
                ('tags', models.ManyToManyField(blank=True, related_name='words', to='dictionary_service.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0.0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='dictionary_service.word')),
            ],
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['word'], name='dictionary__word_42d146_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['translation'], name='dictionary__transla_ee329a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('dictionary', 'word')},
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['word'], name='dictionary__word_id_074c72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together={('word',)},
        ),
    ]
