# Generated by Django 5.1.1 on 2024-11-15 10:12

import dictionary_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'Dictionary', 'verbose_name_plural': 'Dictionaries'},
        ),
        migrations.AlterModelOptions(
            name='userword',
            options={'verbose_name': 'User Word', 'verbose_name_plural': 'User Words'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AddField(
            model_name='dictionary',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=dictionary_service.models.dictionary_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='word',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to=dictionary_service.models.word_image_upload_to),
        ),
    ]
