# Generated by Django 5.1.1 on 2024-11-15 16:50

import dictionary_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_service', '0002_alter_dictionary_options_alter_userword_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to=dictionary_service.models.dictionary_cover_upload_to, validators=[dictionary_service.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='image_path',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to=dictionary_service.models.word_image_upload_to, validators=[dictionary_service.models.validate_image_extension]),
        ),
    ]
