# Generated by Django 5.1.1 on 2024-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_service', '0005_alter_userword_unique_together_alter_userword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=500),
        ),
    ]
