# Generated by Django 5.1.1 on 2025-01-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_service', '0006_alter_word_translation_alter_word_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='highlight_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
