# Generated by Django 5.1.1 on 2025-02-19 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_service', '0007_userword_highlight_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.CreateModel(
            name='DictionaryProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_progress', models.FloatField(default=0.0, help_text='Суммарный прогресс всех слов (0–10)')),
                ('overall_progress', models.FloatField(default=0.0, help_text='Общий прогресс словаря в %')),
                ('group_0_2', models.PositiveIntegerField(default=0, help_text='Слова с прогрессом 0–2')),
                ('group_3_4', models.PositiveIntegerField(default=0, help_text='Слова с прогрессом 3–4')),
                ('group_5_6', models.PositiveIntegerField(default=0, help_text='Слова с прогрессом 5–6')),
                ('group_7_8', models.PositiveIntegerField(default=0, help_text='Слова с прогрессом 7–8')),
                ('group_9_10', models.PositiveIntegerField(default=0, help_text='Слова с прогрессом 9–10')),
                ('dictionary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dictionary_service.dictionary')),
            ],
        ),
    ]
