# Generated by Django 5.1.1 on 2025-02-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_service', '0008_alter_tag_options_dictionaryprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryprogress',
            name='max_progress',
            field=models.FloatField(default=0.0, help_text='Максимальный возможный прогресс (word_count * 10)'),
        ),
    ]
